### PR TITLE
Upgrade black to v20.8b1

### PR DESCRIPTION
**Pull request by skshetry**
`black` had a new release yesterday: https://github.com/psf/black/releases/tag/20.8b1

Btw, are there any plans to auto-update them? Idk, maybe use renovate to update from requirements.txt or package.json?

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks!

> maybe use renovate to update from requirements.txt or package.json?

Can you say more about how this could work?

**Comment by skshetry** [comment]
Most of the time, I only care about the latest version. So, it should just be using renovate/dependabot to update requirements.txt and make docker install from that file (`pip install -r requirements.txt`). 

The version number of docker image could also be auto-incremented. 

If it needs to be tied with the package's version, it might involve extracting the actual version of the installed package or using commit message from renovate, as [it's commit message is _usually_ structured](http://docs.renovatebot.com/configuration-templates). But,  I am not sure if that would be enough for `restylers`.

**Comment by pbrisbin** [comment]
Generally speaking, making the sub-directories proper projects and having the `Dockerfile` copy in the manifest (e.g. `requirements.txt`) makes a lot of sense. And then I think Renovate would automatically manage the `requirements.txt` files correctly.

That's not _totally_ automated updates, only 1 of 2/3 steps, but I think it's a great place to start. The Renovate PRs would at least notify me (or anyone) that we are out of date, and then the manual process would be to merge, tag, build -- which we could seek to automate later.

Thanks for the suggestion!

**Comment by pbrisbin** [comment]
Sorry for the delay here, I'm actually trying to hold this PR open as a test case for more automation in this area, which I hope to spike out this week. Let me know if you just want me to merge it and get the update out quickly.

**Comment by pbrisbin** [comment]
Merged in 5e0a0a33b0d87a195999463913880b5f44e0c498, thank you!

**Pull request closed without merging**
