### PR TITLE
feat(prettier-json): add restyler for prettier-json

### LINKED ISSUE #56: prettier-json
https://prettier.io/

### PR DESCRIPTION
**Pull request by DanielHabenicht**
fixes #56

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
How can I test the restyler? The `make` command failed...

**Comment by pbrisbin** [comment]
Which `make` command did you run? What was the error?

**Comment by DanielHabenicht** [comment]
`make prettier-json/Dockerfile.tested`

**Comment by DanielHabenicht** [comment]
I was going through your docs, https://github.com/restyled-io/restyled.io/wiki/Adding-a-Restyler

**Comment by pbrisbin** [comment]
Yup! I'll take over and get this PR through either way, but I'm curious
what error you're getting.

**Comment by pbrisbin** [comment]
OK, I see what happened. I made some the fixes in https://github.com/restyled-io/restylers/pull/58, FYI.

1. Since this is an "override", the `make` command to test it is slightly different

   ```console
   make prettier-json.tested
   ```

   I think overrides probably require their own documentation and the current "Adding a Restyler" page should just note the caveat and link out.

1. The file should be `info.yaml` (not `info.yml`)
1. You had an `arguments:` key with no value, it either needs a list value, or to not be specified.
1. The test cases needed a `.json` extension to pass

I'll merge that other PR on Green. Thanks!

**Comment by DanielHabenicht** [comment]
Ahh, ok thanks. I might add a PR for your documentation after I test it. 

For your information I copied the test cases from here: 
https://github.com/restyled-io/restylers/blob/master/jq/info.yaml

**Pull request closed without merging**
