### PR TITLE
Feature / Upgrade Terraform

### LINKED ISSUE #74: terraform 0.12
~~I would have opened a PR but it doesn't look like that is supported.~~

The vast majority of the Terraform community has upgraded and moved on to 0.12.x, could we upgrade to the latest version of [0.12.24](https://github.com/hashicorp/terraform/releases)? There are significant improvements in 0.12 (better type system) and this will be a breaking change

### PR DESCRIPTION
**Pull request by bryantbiggs**
- Upgrade terraform version to latest 0.12.24
- Update first test case which is more representative of most formatting issues (also previous test case does not resolve with brack on 2nd line}

Closes #74

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks! I'll merge and once CI is finished.

**Comment by pbrisbin** [comment]
```
The terraform Restyler
Error: Only .tf and .tfvars files can be processed with terraform fmt
  Restyles as expected (FAILED - 1)
```

Hmm, looks like the test cases need to add `extension`? The new version is being stricter about file name I think.

**Comment by pbrisbin** [comment]
@bryantbiggs let me know if you'll take care of that test failure, or if you'd like me to take over at this point.

**Comment by bryantbiggs** [comment]
hey @pbrisbin that would be great. with the hcl code embedded in the yaml files I wouldn't even know where to begin

**Comment by pbrisbin** [comment]
> with the hcl code embedded in the yaml files

Not sure what this means, care to clarify?

> I wouldn't even know where to begin

I try to explain a little in the documentation here: https://github.com/restyled-io/restyled.io/wiki/Restyler-Info-Yaml#maximal-example

```yaml
metadata:
  languages: []
  tests:
    - support:
        path: x.conf
        contents: |
          Content for x.conf
      extension: .foo            # <- see here
      contents: |
        Content before fixing
      restyled: |
        Content after fixing
```

I think all we'll need to do is:

```diff
   tests:
+    - extension: .tf
+      contents: |
-    - contents: |
```

If that gets you going, feel free to take care of it. Otherwise, I'll get to this over the weekend, probably.

**Comment by bryantbiggs** [comment]
ah ok, I didn't see that there. I can add that for sure. and regarding the hcl comment, terraform has a DSL called HCL (actually now HCL2) which is just `hashicorp language`. thanks, I should be able to get to this in a few

**Pull request merged**
