### PR TITLE
chore: Update isort to 5.6.4

### PR DESCRIPTION
**Pull request by CartoonFan**

### CODE REVIEW

**Comment by pbrisbin** [comment]
Oh no, it looks like these we all based on your isort branch and so they conflict.

Can you rebase each of them to to just their commit?

**Comment by CartoonFan** [comment]
Right, I'll try. All this is pretty new to me...

**Comment by pbrisbin** [comment]
It's OK if it's giving you trouble. Just let me know and I'll collect all your PRs into a new one and merge that instead.

**Comment by CartoonFan** [comment]
Thanks. I tried to rebase the branches as best as I could, but if it still needs fixing, I'm willing to help.

**Comment by pbrisbin** [comment]
Ah you know what, since you're a fork it'll be slightly trickier.

I'm happy to just take over on my end, but if you're interested in learning and trying things out, I think you'd want to do somethign like the following:

Add my repository as a new remote named `upstream` and fetch it:

```
git remote add upstream https://github.com/restyled-io/restylers
git fetch upstream
```

Rebase your branch over my latest version of `master`, interactively:

```
git rebase -i upstream/master
```

Your editor will open with a list of commits. Here you can remove, squash, and reorder by changing these lines.

What you want to do is delete all lines *except* the one commit you want, "chore: update isort to 5.6.4". Then push up to your branch. You'll need to force here because you've rewritten history.

```
git push --force
```

If if you mess anything up you can always use `git reflog` to look at the various states then `git reset --hard` to a known point and `git push --force` it again to get back.

Again, if you don't feel like messing with this I'm happy to take over.

**Comment by CartoonFan** [comment]
Is it better now? I'm honestly not sure. This whole trip has been pretty fun, though.

**Comment by pbrisbin** [comment]
Haha, 'fraid not. Can you see how this is showing 23 commits? https://github.com/restyled-io/restylers/pull/105/commits

We are trying to make it show only one :smile:

**Comment by CartoonFan** [comment]
Ha, I figured as much. I ran into trouble and tried to fix it myself, so naturally something like this happens :laughing:. I removed the commits, but wasn't on my branch, so the push failed, and I wasn't sure what to do. I tried to resolve things myself, and then this happened...

**Comment by pbrisbin** [comment]
Do you know how to chat in IRC? We could work through this more synchronously in `#restyled` on freenode. I'll be online for another hour or so.

I think it would be tough to have the back and forth required to sort this out otherwise, so if not I'll just take over from here.

**Comment by CartoonFan** [comment]
I've done IRC before, and while I would love to learn more, I unfortunately don't think I can commit the time right now, so it may be up to you. Thanks for the offer, though, and I apologize for the inconvenience I caused :sweat_smile: .

**Comment by pbrisbin** [comment]
Merging via #111 instead.

**Pull request closed without merging**
