### PR TITLE
black: version bump 19.3b0 -> 19.10b0

### PR DESCRIPTION
**Pull request by mroutis**

### CODE REVIEW

**Comment by mroutis** [comment]
tests failing, issue related: https://github.com/psf/black/issues/1112

**Comment by pbrisbin** [comment]
Thanks! Feel free to add the `gcc` install to the `Dockerfile` if you don't want to wait for that Issue to be resolved.

**Comment by mroutis** [comment]
awesome, @pbrisbin !

**Comment by mroutis** [comment]
@pbrisbin , let's wait a couple of days, looks like there's already a patch that will produce linux wheels

**Comment by mroutis** [comment]
@pbrisbin , patch got merged already :)

could you please trigger the Travis CI build?

**Comment by pbrisbin** [comment]
Nice!

> could you please trigger the Travis CI build?

Since this is your branch, it's actually easier if you do it. Any of,

- `commit --allow-empty` + push
- `commit --amend` + force-push
- `rebase...` + force-push

would work.

If you'd rather I do, I'll have to create my own new branch and PR. Which is fine, but above seems easier. Let me know!

**Comment by pbrisbin** [comment]
Hmm, failed the same way. If I'm reading the [GitHub UI](https://github.com/psf/black/commit/9ef8e6c9b0090d787953bcd3c46a8942483fcc6b) correctly, it seems the commit that bumps `regex` is only on `master` and not released in any version yet.

**Comment by mroutis** [comment]
yikes, I was too excited about it that I forgot they needed to release a new version :disappointed: 

Not sure how it will happen, months may pass without any release.

**Comment by mroutis** [comment]
@pbrisbin, I think that black is not going to release a new version soon :see_no_evil: 

would you be willing to include `gcc` as you previously stated?

**Comment by pbrisbin** [comment]
Haha, thanks for staying on top of this.

**Pull request merged**
