### PR TITLE
Add prettier plugin to sort imports

### PR DESCRIPTION
**Pull request by jason-lieb**
I added a plugin to prettier config to sort imports. This currently breaks restyler when it isn't installed. I think the fix is as simple as just adding the dependency to package.json

### CODE REVIEW

**Comment by pbrisbin** [comment]
Sounds good! Would it be possible to add a new test case that shows sorting working?

https://github.com/restyled-io/restylers/blob/main/prettier/info.yaml#L18-L46

**Comment by pbrisbin** [comment]
FYI, it's [not too cumbersome](https://github.com/restyled-io/restylers/wiki/Adding-a-Restyler#prerequisites) to [run the tests locally](https://github.com/restyled-io/restylers/wiki/Adding-a-Restyler#2-test-locally), if you want to tighten your feedback loop.

**Comment by pbrisbin** [comment]
I wonder if the issue is conflicting `.prettierrc`s...

```
2024-11-20 19:06:56 [info     ] CREATE                          path=prettier-test-1.js
2024-11-20 19:06:56 [info     ] CREATE                          path=prettier-test-2.js
2024-11-20 19:06:56 [info     ] CREATE                          path=tailwind.config.js
2024-11-20 19:06:56 [info     ] CREATE                          path=prettier-test-3.js
2024-11-20 19:06:56 [info     ] CREATE                          path=.prettierrc <-- your file
2024-11-20 19:06:56 [info     ] CREATE                          path=prettier-json-test-1.json
2024-11-20 19:06:56 [info     ] CREATE                          path=prettier-markdown-test-1.md
2024-11-20 19:06:56 [info     ] CREATE                          path=.prettierrc <-- not your file?
2024-11-20 19:06:56 [info     ] CREATE                          path=prettier-yaml-test-1.yaml
```

I can't quite remember where things go when doing these tests, but I know there are isolation issues

**Comment by jason-lieb** [comment]
@pbrisbin I think I ran out of things to test. I'm getting this error on `restyled-fork`: `Error:  Cannot find package '@trivago/prettier-plugin-sort-imports' imported from /code/noop.js`, so it is at least reading the config. I've tried linking the plugin with yarn like you did with tailwind, but that doesn't seem to be working

**Comment by pbrisbin** [comment]
Thanks for fighting with it, I'll try out some things.

**Comment by pbrisbin** [comment]
OK, so I've isolated the issues and have things working locally.

It was the configurations colliding. `just test prettier` passes, while `just test prettier prettier-markdown` fails because, in the latter, the markdown configuration overrides. You might've addressed this with one of your commits, but then failed due to the second issue: you indeed need the link/unlink, so good catch.

I'm going to try and make a more robust fix to the test suite for the colliding support file issue.

**Comment by jason-lieb** [comment]
Awesome thanks! I definitely felt like there were multiple issues happening simultaneously

**Pull request merged**
