### PR TITLE
Bump stylish-haskell to v0.9.2.2

### PR DESCRIPTION
**Pull request by fizruk**
This fixes stylish-haskell for `BlockArguments` extension.

I guess you will upload the new image yourself?
I don't see a CI config for that and I assume I don't have rights to do that myself :)

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks! Yes, I'll have to take it from here. CI is a nice-to-have on my TODO for now :)

**Comment by pbrisbin** [comment]
The updated image is now available to use in your `restylers[hlint].image` key. It'll be a little while before it's being used by default. Thanks!

**Comment by fizruk** [comment]
Great, thanks!

> The updated image is now available to use in your `restylers[hlint].image` key.

Did you mean `restylers[stylish-haskell].image`? 😅

**Comment by pbrisbin** [comment]
Haha, sorry about that. I wonder what would happen if you configured one Restyler's image under another's name... :thinking:

**Pull request merged**
